export const ADD_EXT_CHECK_URL = 'ADD_EXT_CHECK_URL'
export const ADD_EXT_STEP_BACK = 'ADD_EXT_STEP_BACK'
export const ADD_EXT_UPLOAD_IMAGES = 'ADD_EXT_UPLOAD_IMAGES'
export const ADD_EXT_SUBMIT = 'ADD_EXT_SUBMIT'
